version: '3'

services:
  db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: carrot
      POSTGRES_USER: carrot
      POSTGRES_DB: carrot
